addSbtPlugin("com.typesafe.sbt"      % "sbt-osgi"            % "0.9.6")
addSbtPlugin("org.scalariform"       % "sbt-scalariform"     % "1.8.3")
addSbtPlugin("com.typesafe.sbt"      % "sbt-site"            % "1.4.1")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"          % "5.6.0")
addSbtPlugin("com.typesafe"          % "sbt-mima-plugin"     % "1.0.1")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.9.2")
addSbtPlugin("com.geirsson"          % "sbt-ci-release"      % "1.5.7")
