addSbtPlugin("com.typesafe.sbt"      % "sbt-osgi"            % "0.9.6")
addSbtPlugin("org.scalariform"       % "sbt-scalariform"     % "1.8.3")
addSbtPlugin("com.typesafe.sbt"      % "sbt-site"            % "1.4.1")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"          % "5.6.5")
addSbtPlugin("com.typesafe"          % "sbt-mima-plugin"     % "1.0.1")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.10.6")
addSbtPlugin("com.github.sbt"          % "sbt-ci-release"      % "1.5.10")
